### ISSUE TITLE
Not compilint with node v10.13.0 LTS

### ISSUE THREAD

**Issue by NameFILIP** [candu/node-int64-native#23]
**Step 1**

```
  test-node-10 yarn init
yarn init v1.12.1
question name (test-node-10): 
question version (1.0.0): 
question description: 
question entry point (index.js): 
question repository url: 
question author: 
question license (MIT): 
question private: 
success Saved package.json
✨  Done in 3.34s.
```

**Step 2**

```
➜  test-node-10 nvm use 10
Now using node v10.13.0 (npm v6.4.1)
```

**Step 3**

```
➜  test-node-10 yarn add int64-native
yarn add v1.10.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
error /Users/myusername/Dev/test-node-10/node_modules/int64-native: Command failed.
Exit code: 1
Command: node-gyp configure && node-gyp build
Arguments: 
Directory: /Users/myusername/Dev/test-node-10/node_modules/int64-native
Output:
CXX(target) Release/obj.target/Int64/src/main.o
In file included from ../src/main.cc:8:
In file included from ../src/Int64.h:5:
In file included from ../../nan/nan.h:222:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:340:28: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::StringObject::New(value).As<v8::StringObject>();
                           ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:5052:3: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/main.cc:8:
In file included from ../src/Int64.h:5:
../../nan/nan.h:1066:44: warning: 'ToString' is deprecated [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString();
                                           ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2454:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/main.cc:8:
In file included from ../src/Int64.h:5:
../../nan/nan.h:1080:27: warning: 'WriteUtf8' is deprecated [-Wdeprecated-declarations]
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                          ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2658:3: note: 'WriteUtf8' has been explicitly marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
3 warnings generated.
  CXX(target) Release/obj.target/Int64/src/Int64.o
In file included from ../src/Int64.cc:12:
In file included from ../src/Int64.h:5:
In file included from ../../nan/nan.h:222:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:340:28: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::StringObject::New(value).As<v8::StringObject>();
                           ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:5052:3: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/Int64.cc:12:
In file included from ../src/Int64.h:5:
../../nan/nan.h:1066:44: warning: 'ToString' is deprecated [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString();
                                           ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2454:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/Int64.cc:12:
In file included from ../src/Int64.h:5:
../../nan/nan.h:1080:27: warning: 'WriteUtf8' is deprecated [-Wdeprecated-declarations]
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                          ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2658:3: note: 'WriteUtf8' has been explicitly marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Int64.cc:53:37: warning: 'NumberValue' is deprecated [-Wdeprecated-declarations]
  mValue = static_cast<uint64_t>(n->NumberValue());
                                    ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2475:3: note: 'NumberValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", double NumberValue() const);
  ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Int64.cc:57:49: warning: 'NumberValue' is deprecated [-Wdeprecated-declarations]
  uint32_t highBits = static_cast<uint32_t>(hi->NumberValue());
                                                ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2475:3: note: 'NumberValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", double NumberValue() const);
  ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Int64.cc:58:48: warning: 'NumberValue' is deprecated [-Wdeprecated-declarations]
  uint32_t lowBits = static_cast<uint32_t>(lo->NumberValue());
                                               ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2475:3: note: 'NumberValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", double NumberValue() const);
  ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Int64.cc:65:21: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  String::Utf8Value utf8(s);
                    ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2891:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Int64.cc:85:34: error: no matching member function for call to 'ToNumber'
        obj = new Int64(info[0]->ToNumber());
                        ~~~~~~~~~^~~~~~~~
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2425:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Number> ToNumber(
                                           ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2442:31: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                Local<Number> ToNumber(Isolate* isolate) const);
                              ^
../src/Int64.cc:87:34: warning: 'ToString' is deprecated [-Wdeprecated-declarations]
        obj = new Int64(info[0]->ToString());
                                 ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2454:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Int64.cc:91:34: error: no matching member function for call to 'ToNumber'
        obj = new Int64(info[0]->ToNumber(), info[1]->ToNumber());
                        ~~~~~~~~~^~~~~~~~
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2425:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Number> ToNumber(
                                           ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2442:31: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                Local<Number> ToNumber(Isolate* isolate) const);
                              ^
../src/Int64.cc:91:55: error: no matching member function for call to 'ToNumber'
        obj = new Int64(info[0]->ToNumber(), info[1]->ToNumber());
                                             ~~~~~~~~~^~~~~~~~
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2425:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Number> ToNumber(
                                           ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2442:31: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                Local<Number> ToNumber(Isolate* isolate) const);
                              ^
../src/Int64.cc:104:39: error: no matching member function for call to 'NewInstance'
      info.GetReturnValue().Set(cons->NewInstance(0, argv));
                                ~~~~~~^~~~~~~~~~~
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:3996:44: note: candidate function not viable: requires single argument 'context', but 2 arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:3993:44: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
../src/Int64.cc:107:39: error: no matching member function for call to 'NewInstance'
      info.GetReturnValue().Set(cons->NewInstance(1, argv));
                                ~~~~~~^~~~~~~~~~~
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:3996:44: note: candidate function not viable: requires single argument 'context', but 2 arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:3993:44: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
../src/Int64.cc:110:39: error: no matching member function for call to 'NewInstance'
      info.GetReturnValue().Set(cons->NewInstance(2, argv));
                                ~~~~~~^~~~~~~~~~~
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:3996:44: note: candidate function not viable: requires single argument 'context', but 2 arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:3993:44: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
../src/Int64.cc:165:56: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
  Int64* otherObj = ObjectWrap::Unwrap<Int64>(info[0]->ToObject());
                                                       ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Int64.cc:178:56: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
  Int64* otherObj = ObjectWrap::Unwrap<Int64>(info[0]->ToObject());
                                                       ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Int64.cc:208:53: error: no matching member function for call to 'ToNumber'
  uint64_t shiftBy = static_cast<uint64_t>(info[0]->ToNumber()->NumberValue());
                                           ~~~~~~~~~^~~~~~~~
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2425:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Number> ToNumber(
                                           ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2442:31: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                Local<Number> ToNumber(Isolate* isolate) const);
                              ^
../src/Int64.cc:215:34: error: no matching member function for call to 'NewInstance'
  Local<Object> instance = cons->NewInstance(2, argv);
                           ~~~~~~^~~~~~~~~~~
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:3996:44: note: candidate function not viable: requires single argument 'context', but 2 arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:3993:44: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
../src/Int64.cc:229:53: error: no matching member function for call to 'ToNumber'
  uint64_t shiftBy = static_cast<uint64_t>(info[0]->ToNumber()->NumberValue());
                                           ~~~~~~~~~^~~~~~~~
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2425:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Number> ToNumber(
                                           ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2442:31: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                Local<Number> ToNumber(Isolate* isolate) const);
                              ^
../src/Int64.cc:236:34: error: no matching member function for call to 'NewInstance'
  Local<Object> instance = cons->NewInstance(2, argv);
                           ~~~~~~^~~~~~~~~~~
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:3996:44: note: candidate function not viable: requires single argument 'context', but 2 arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:3993:44: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
../src/Int64.cc:248:36: warning: 'IntegerValue' is deprecated [-Wdeprecated-declarations]
    value = obj->mValue & info[0]->IntegerValue();
                                   ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2476:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Int64.cc:250:58: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
    Int64* otherObj = ObjectWrap::Unwrap<Int64>(info[0]->ToObject());
                                                         ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Int64.cc:261:34: error: no matching member function for call to 'NewInstance'
  Local<Object> instance = cons->NewInstance(2, argv);
                           ~~~~~~^~~~~~~~~~~
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:3996:44: note: candidate function not viable: requires single argument 'context', but 2 arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:3993:44: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
../src/Int64.cc:273:36: warning: 'IntegerValue' is deprecated [-Wdeprecated-declarations]
    value = obj->mValue | info[0]->IntegerValue();
                                   ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2476:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Int64.cc:275:58: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
    Int64* otherObj = ObjectWrap::Unwrap<Int64>(info[0]->ToObject());
                                                         ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Int64.cc:286:34: error: no matching member function for call to 'NewInstance'
  Local<Object> instance = cons->NewInstance(2, argv);
                           ~~~~~~^~~~~~~~~~~
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:3996:44: note: candidate function not viable: requires single argument 'context', but 2 arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:3993:44: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
../src/Int64.cc:298:36: warning: 'IntegerValue' is deprecated [-Wdeprecated-declarations]
    value = obj->mValue ^ info[0]->IntegerValue();
                                   ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2476:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Int64.cc:300:58: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
    Int64* otherObj = ObjectWrap::Unwrap<Int64>(info[0]->ToObject());
                                                         ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Int64.cc:311:34: error: no matching member function for call to 'NewInstance'
  Local<Object> instance = cons->NewInstance(2, argv);
                           ~~~~~~^~~~~~~~~~~
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:3996:44: note: candidate function not viable: requires single argument 'context', but 2 arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:3993:44: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
../src/Int64.cc:323:36: warning: 'IntegerValue' is deprecated [-Wdeprecated-declarations]
    value = obj->mValue + info[0]->IntegerValue();
                                   ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2476:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Int64.cc:325:58: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
    Int64* otherObj = ObjectWrap::Unwrap<Int64>(info[0]->ToObject());
                                                         ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Int64.cc:336:34: error: no matching member function for call to 'NewInstance'
  Local<Object> instance = cons->NewInstance(2, argv);
                           ~~~~~~^~~~~~~~~~~
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:3996:44: note: candidate function not viable: requires single argument 'context', but 2 arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:3993:44: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
../src/Int64.cc:348:36: warning: 'IntegerValue' is deprecated [-Wdeprecated-declarations]
    value = obj->mValue - info[0]->IntegerValue();
                                   ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2476:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Int64.cc:350:58: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
    Int64* otherObj = ObjectWrap::Unwrap<Int64>(info[0]->ToObject());
                                                         ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/Int64.cc:361:34: error: no matching member function for call to 'NewInstance'
  Local<Object> instance = cons->NewInstance(2, argv);
                           ~~~~~~^~~~~~~~~~~
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:3996:44: note: candidate function not viable: requires single argument 'context', but 2 arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/myusername/.node-gyp/10.13.0/include/node/v8.h:3993:44: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
20 warnings and 15 errors generated.
make: *** [Release/obj.target/Int64/src/Int64.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/myusername/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/Users/myusername/.nvm/versions/node/v10.13.0/bin/node" "/Users/myusername/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /Users/myusername/Dev/test-node-10/node_modules/int64-native
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
➜  test-node-10 
```

**Comment by Matt-Esch** [comment]
See: https://github.com/candu/node-int64-native/pull/24
