### ISSUE TITLE
Not compiling with node v12.6.0

### ISSUE THREAD

**Issue by CarlosJimenez** [candu/node-int64-native#26]
int64-native@0.5.0 install 
> node-gyp configure && node-gyp build

  CXX(target) Release/obj.target/Int64/src/main.o
In file included from ../src/main.cc:8:
../src/Int64.h:13:20: error: no template named 'Handle'
  static void Init(Handle<Object> exports);
                   ^
../src/main.cc:13:6: error: variable has incomplete type 'void'
void InitAll(Handle<Object> exports) {
     ^
../src/main.cc:13:21: error: 'Object' does not refer to a value
void InitAll(Handle<Object> exports) {
                    ^
/Users/.../.node-gyp/12.6.0/include/node/v8.h:3356:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
../src/main.cc:13:14: error: use of undeclared identifier 'Handle'
void InitAll(Handle<Object> exports) {
             ^
../src/main.cc:13:29: error: use of undeclared identifier 'exports'
void InitAll(Handle<Object> exports) {
                            ^
../src/main.cc:13:37: error: expected ';' after top level declarator
void InitAll(Handle<Object> exports) {

**Comment by 278kunal** [comment]
Fails to build even on Node 12.13.0

error /Users/testUser/workspace/project/node_modules/int64-native: Command failed.
Exit code: 1
Command: node-gyp configure && node-gyp build
Arguments:
Directory: /Users/testUser/workspace/project/node_modules/int64-native
Output:
CXX(target) Release/obj.target/Int64/src/main.o
In file included from ../src/main.cc:8:
../src/Int64.h:13:20: error: no template named 'Handle'
  static void Init(Handle<Object> exports);
                   ^
../src/main.cc:13:14: error: no template named 'Handle'
void InitAll(Handle<Object> exports) {
             ^
2 errors generated.
make: *** [Release/obj.target/Int64/src/main.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/testUser/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/testUser/.nvm/versions/node/v12.13.0/bin/node" "/Users/testUser/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /Users/testUser/workspace/project/node_modules/int64-native
